Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\pande\Anaconda3\lib\site-packages\SigProfilerMatrixGenerator\scripts\SigProfilerMatrixGeneratorFunc.py", line 371, in SigProfilerMatrixGeneratorFunc
    samples = sorted(samples)
UnboundLocalError: local variable 'samples' referenced before assignment
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\pande\Anaconda3\lib\site-packages\SigProfilerMatrixGenerator\scripts\SigProfilerMatrixGeneratorFunc.py", line 274, in SigProfilerMatrixGeneratorFunc
    os.makedirs(vcf_path, exist_ok=True)
  File "C:\Users\pande\Anaconda3\lib\os.py", line 221, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'tcga_laml.maf/input/'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\pande\Anaconda3\lib\site-packages\SigProfilerMatrixGenerator\scripts\SigProfilerMatrixGeneratorFunc.py", line 274, in SigProfilerMatrixGeneratorFunc
    os.makedirs(vcf_path, exist_ok=True)
  File "C:\Users\pande\Anaconda3\lib\os.py", line 221, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'tcga_laml.maf/input/'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\pande\Anaconda3\lib\site-packages\SigProfilerMatrixGenerator\scripts\SigProfilerMatrixGeneratorFunc.py", line 274, in SigProfilerMatrixGeneratorFunc
    os.makedirs(vcf_path, exist_ok=True)
  File "C:\Users\pande\Anaconda3\lib\os.py", line 221, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'tcga_laml.maf/input/'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'matrices' is not defined

